# Generated by Django 2.2.12 on 2022-02-26 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_book_info'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table='book',
        ),
    ]
